# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stop_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=10)),
                ('stop_lat', models.CharField(max_length=20)),
                ('stop_long', models.CharField(max_length=20)),
            ],
        ),
    ]
