# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_route_and_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_and_stop',
            name='stop_id',
            field=models.CharField(max_length=10),
        ),
    ]
