# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170620_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='route_and_stop',
        ),
        migrations.DeleteModel(
            name='stop_locations',
        ),
    ]
